spring.application.name=ecom-proj
server.port=${PORT:8081}

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/ecommerce;AUTO_SERVER=TRUE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:project1}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql

# H2 Console (visit http://localhost:8080/h2-console while backend is running)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console